### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Subbaraju6** [ZYunfeii/UAV_Obstacle_Avoiding_DRL#1]
Hello sir,I was unable to run this please look into it sir Here I am attaching the images.please help sir as it was relating to my project.
![IMG-20220305-WA0014](https://user-images.githubusercontent.com/95461761/156887885-324e0aec-c7d0-402e-9ea7-49dbd30493a1.jpg)
![IMG-20220305-WA0013](https://user-images.githubusercontent.com/95461761/156887887-31b41d3e-947f-40c8-b9e6-c964c4b9f077.jpg)

**Comment by ZYunfeii** [comment]
I can only reply to the question for my repo.
