### ISSUE TITLE
what‘s ’the meaning of three actions?

### ISSUE THREAD

**Issue by xiaominy** [ZYunfeii/UAV_Obstacle_Avoiding_DRL#2]
Hi, this is a wonderful job!
But, i can't understand the meaning of row0, theta, sigma0.  Great thanks if u reply this issue!

`def getqNext(self, uavPos, obsCenter, vObs, row0, sigma0, theta, qBefore):
        u = self.initField(uavPos, self.V0, self.goal)
        repulsiveMatrix = self.calRepulsiveMatrix(uavPos, obsCenter, self.obsR, row0)
        tangentialMatrix = self.calTangentialMatrix(uavPos, obsCenter, self.obsR, theta, sigma0)
        T = self.calculateT(obsCenter, uavPos, self.obsR)
        vp = np.exp(-T / self.lam) * vObs
        M = np.eye(3) + repulsiveMatrix + tangentialMatrix
        ubar = (M.dot(u - vp.reshape(-1, 1)).T + vp.reshape(1, -1)).squeeze()
        # 限制ubar的模长，避免进入障碍内部后轨迹突变
        if self.calVecLen(ubar) > 5:
            ubar = ubar/self.calVecLen(ubar)*5
        if qBefore[0] is None:
            uavNextPos = uavPos + ubar * self.stepSize
        else:
            uavNextPos = uavPos + ubar * self.stepSize
            _, _, _, _, qNext = self.kinematicConstrant(uavPos, qBefore, uavNextPos)
        return uavNextPos`

**Comment by xiaominy** [comment]
Is row0, theta, sigma0 means pitch angle, course angle, acceleration or someting else?
And i can't quite understand the way u calculate the uav's next positon, like `calRepulsiveMatrix` ,`calTangentialMatrix` , what's the calculation principle?

**Comment by ZYunfeii** [comment]
they are parameters of the algorithm named ifds.

**Comment by xiaominy** [comment]
Thanks for your reply! But i have another question: why u use DRL to train repulsive parameter and  tangential parameter? I think they are the inherent property of an obstacle. Thus, for a certain obstacle, it couldn't be changed. Do i understand correctly? And what's the purpose by using DRL to train the algorithm's parameters?
